apiVersion: v1
kind: Service
metadata:
  name: autocloud-redis
  namespace: autocloud
spec:
  selector:
    app: autocloud
    tier: redis
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autocloud-redis
  namespace: autocloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autocloud
      tier: redis
  template:
    metadata:
      labels:
        app: autocloud
        tier: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        args: ["--appendonly", "yes"]